language: python
dist: focal
sudo: required
cache: pip
matrix:
  include:
    - python: 3.8
    - python: 3.9-dev
    - python: nightly
  allow_failures:
    - python: nightly
before_install:
  - pip install -r requirements-dev.txt
script:
  - make flake8
  - make mypy
  # Run bot (in read only mode, on a single project) as a smoke test
  - ./repology-wikidata-bot.py --dry-run --verbose --from firefox --to firefox
