language: python
dist: xenial
sudo: required
cache: pip
matrix:
  include:
    - python: 3.7
    - python: 3.8-dev
    - python: nightly
  allow_failures:
    - python: 3.8-dev
    - python: nightly
before_install:
  - pip install pywikibot
  - pip install requests

  # devel depends
  - pip install flake8
  - pip install flake8-builtins
  - pip install flake8-import-order
  - pip install flake8-quotes
  - pip install mypy

script:
  - mypy repology-wikidata-bot.py
  - flake8
